# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='math_type',
            field=models.CharField(choices=[('Addition', 'Addition'), ('Subtraction', 'Subtraction'), ('Odd/Even', 'Odd/Even')], max_length=15),
        ),
    ]
