# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-21 22:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.BaseModel')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('expected_completion', models.DateTimeField()),
                ('finished_at', models.DateTimeField(null=True)),
                ('parent_goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.Goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('utils.basemodel',),
        ),
    ]
