# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='parent_goal',
            new_name='bigger_goal',
        ),
    ]
