# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20170309_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='bigger_goal',
            new_name='future_goal',
        ),
    ]
